//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContabilWindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contas()
        {
            this.PlanoDeContasDetalhes = new HashSet<PlanoDeContasDetalhes>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public bool AtivoContaSintetica { get; set; }
        public bool AtivoContaAnalitica { get; set; }
        public bool PassivoContaSintetica { get; set; }
        public bool PassivoContaAnalitica { get; set; }
        public bool ReceitaContaSintetica { get; set; }
        public bool ReceitaContaAnalitica { get; set; }
        public bool DespesaContaSintetica { get; set; }
        public bool DespesaContaAnalitica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanoDeContasDetalhes> PlanoDeContasDetalhes { get; set; }
    }
}
