//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContabilWindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contas()
        {
            this.Lancamentos = new HashSet<Lancamentos>();
            this.Lancamentos1 = new HashSet<Lancamentos>();
            this.Lancamentos11 = new HashSet<Lancamentos>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Classificacao { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamentos> Lancamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamentos> Lancamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lancamentos> Lancamentos11 { get; set; }
    }
}
