//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContabilWindowsFormsApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ContabilEntities : DbContext
    {
        public ContabilEntities()
            : base("name=ContabilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contas> Contas { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<PlanoDeContas> PlanoDeContas { get; set; }
        public virtual DbSet<PlanoDeContasDetalhes> PlanoDeContasDetalhes { get; set; }
    
        public virtual int sp_AtivoCadastrarContaAnalitica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AtivoCadastrarContaAnalitica", codigoParameter, nomeParameter);
        }
    
        public virtual int sp_AtivoCadastrarContaSintetica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AtivoCadastrarContaSintetica", codigoParameter, nomeParameter);
        }
    
        public virtual ObjectResult<sp_ContasListarTodas_Result> sp_ContasListarTodas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ContasListarTodas_Result>("sp_ContasListarTodas");
        }
    
        public virtual int sp_DespesaCadastrarContaAnalitica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DespesaCadastrarContaAnalitica", codigoParameter, nomeParameter);
        }
    
        public virtual int sp_DespesaCadastrarContaSintetica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DespesaCadastrarContaSintetica", codigoParameter, nomeParameter);
        }
    
        public virtual int sp_EmpresaAlterar(Nullable<int> id, string razaoSocial)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var razaoSocialParameter = razaoSocial != null ?
                new ObjectParameter("razaoSocial", razaoSocial) :
                new ObjectParameter("razaoSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmpresaAlterar", idParameter, razaoSocialParameter);
        }
    
        public virtual ObjectResult<sp_EmpresaBuscar_Result> sp_EmpresaBuscar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmpresaBuscar_Result>("sp_EmpresaBuscar", idParameter);
        }
    
        public virtual int sp_EmpresaCadastrar(string razaoSocial)
        {
            var razaoSocialParameter = razaoSocial != null ?
                new ObjectParameter("razaoSocial", razaoSocial) :
                new ObjectParameter("razaoSocial", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmpresaCadastrar", razaoSocialParameter);
        }
    
        public virtual ObjectResult<sp_EmpresasListarTodas_Result> sp_EmpresasListarTodas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmpresasListarTodas_Result>("sp_EmpresasListarTodas");
        }
    
        public virtual int sp_PassivoCadastrarContaAnalitica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PassivoCadastrarContaAnalitica", codigoParameter, nomeParameter);
        }
    
        public virtual int sp_PassivoCadastrarContaSintetica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PassivoCadastrarContaSintetica", codigoParameter, nomeParameter);
        }
    
        public virtual int sp_PlanoDeContasAdicionarConta(Nullable<int> idPlanoDeContas, Nullable<int> idConta, string classificacao)
        {
            var idPlanoDeContasParameter = idPlanoDeContas.HasValue ?
                new ObjectParameter("idPlanoDeContas", idPlanoDeContas) :
                new ObjectParameter("idPlanoDeContas", typeof(int));
    
            var idContaParameter = idConta.HasValue ?
                new ObjectParameter("idConta", idConta) :
                new ObjectParameter("idConta", typeof(int));
    
            var classificacaoParameter = classificacao != null ?
                new ObjectParameter("classificacao", classificacao) :
                new ObjectParameter("classificacao", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PlanoDeContasAdicionarConta", idPlanoDeContasParameter, idContaParameter, classificacaoParameter);
        }
    
        public virtual int sp_PlanoDeContasCriarNovoPlano(Nullable<int> idEmpresa, string mesDoPlano)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var mesDoPlanoParameter = mesDoPlano != null ?
                new ObjectParameter("mesDoPlano", mesDoPlano) :
                new ObjectParameter("mesDoPlano", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PlanoDeContasCriarNovoPlano", idEmpresaParameter, mesDoPlanoParameter);
        }
    
        public virtual int sp_PlanoDeContasRemoverConta(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PlanoDeContasRemoverConta", idParameter);
        }
    
        public virtual ObjectResult<sp_PlanosDeContasListarTodosPlanosDaEmpresa_Result> sp_PlanosDeContasListarTodosPlanosDaEmpresa(Nullable<int> idEmpresa)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PlanosDeContasListarTodosPlanosDaEmpresa_Result>("sp_PlanosDeContasListarTodosPlanosDaEmpresa", idEmpresaParameter);
        }
    
        public virtual int sp_ReceitaCadastrarContaAnalitica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ReceitaCadastrarContaAnalitica", codigoParameter, nomeParameter);
        }
    
        public virtual int sp_ReceitaCadastrarContaSintetica(string codigo, string nome)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ReceitaCadastrarContaSintetica", codigoParameter, nomeParameter);
        }
    
        public virtual ObjectResult<sp_ContaBuscar_Result> sp_ContaBuscar(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ContaBuscar_Result>("sp_ContaBuscar", idParameter);
        }
    
        public virtual ObjectResult<sp_PlanoDeContasListarContasDoPlano_Result> sp_PlanoDeContasListarContasDoPlano(Nullable<int> idPlanoDeContas)
        {
            var idPlanoDeContasParameter = idPlanoDeContas.HasValue ?
                new ObjectParameter("idPlanoDeContas", idPlanoDeContas) :
                new ObjectParameter("idPlanoDeContas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PlanoDeContasListarContasDoPlano_Result>("sp_PlanoDeContasListarContasDoPlano", idPlanoDeContasParameter);
        }
    
        public virtual ObjectResult<sp_PlanoDeContasListarContasForaDoPlano_Result> sp_PlanoDeContasListarContasForaDoPlano(Nullable<int> idPlanoDeContas)
        {
            var idPlanoDeContasParameter = idPlanoDeContas.HasValue ?
                new ObjectParameter("idPlanoDeContas", idPlanoDeContas) :
                new ObjectParameter("idPlanoDeContas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PlanoDeContasListarContasForaDoPlano_Result>("sp_PlanoDeContasListarContasForaDoPlano", idPlanoDeContasParameter);
        }
    }
}
