//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContabilWindowsFormsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanoDeContasDetalhes
    {
        public int Id { get; set; }
        public int IdPlanoDeContas { get; set; }
        public int IdConta { get; set; }
        public string Classificacao { get; set; }
    
        public virtual Contas Contas { get; set; }
        public virtual PlanoDeContas PlanoDeContas { get; set; }
    }
}
